tap "adoptopenjdk/openjdk"
tap "cmacrae/formulae"
tap "danger/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "ngrok/ngrok"
tap "wez/wezterm"
brew "act"
brew "anyenv"
brew "jpeg-xl"
brew "aom"
brew "automake"
brew "openssl@3"
brew "asdf"
brew "autojump"
brew "bat"
brew "grpc"
brew "bear"
brew "berkeley-db", link: true
brew "bottom"
brew "glib"
brew "carthage"
brew "chezmoi"
brew "cmake"
brew "dbmate"
brew "deno"
brew "duf"
brew "dust"
brew "fd"
brew "unbound"
brew "gnutls"
brew "harfbuzz"
brew "libass"
brew "pango"
brew "tesseract"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "gdk-pixbuf"
brew "gh"
brew "ghq"
brew "git"
brew "git-lfs"
brew "glow"
brew "gobject-introspection"
brew "librsvg"
brew "graphviz"
brew "guile"
brew "hub"
brew "shared-mime-info"
brew "libheif"
brew "imagemagick"
brew "jq"
brew "krb5"
brew "libfido2"
brew "llvm"
brew "lsd"
brew "mas"
brew "mecab"
brew "mecab-ipadic"
brew "mysql", restart_service: true
brew "neofetch"
brew "neovim"
brew "nghttp2"
brew "node"
brew "peco"
brew "postgresql@14"
brew "python@3.10"
brew "python@3.9"
brew "ripgrep"
brew "source-highlight"
brew "starship"
brew "tcl-tk", link: false
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tree"
brew "vagrant-completion"
brew "vim"
brew "viu"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "yt-dlp"
brew "zoxide"
brew "zsh-syntax-highlighting"
brew "cmacrae/formulae/spacebar"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
cask "alfred", args: { appdir: "/Applications" }
cask "alt-tab"
cask "android-platform-tools", args: { appdir: "/Applications" }
cask "android-studio"
cask "anki", args: { appdir: "/Applications" }
cask "arc"
cask "background-music"
cask "brooklyn", args: { appdir: "/Applications" }
cask "cleanshot"
cask "discord", args: { appdir: "/Applications" }
cask "docker", args: { appdir: "/Applications" }
cask "dotnet-sdk"
cask "figma", args: { appdir: "/Applications" }
cask "font-fontawesome"
cask "font-hack-nerd-font", args: { appdir: "/Applications" }
cask "google-japanese-ime"
cask "graphiql"
cask "iterm2", args: { appdir: "/Applications" }
cask "karabiner-elements", args: { appdir: "/Applications" }
cask "keycastr", args: { appdir: "/Applications" }
cask "ngrok"
cask "notion", args: { appdir: "/Applications" }
cask "notion-calendar"
cask "obsidian"
cask "postman", args: { appdir: "/Applications" }
cask "raycast"
cask "sequel-ace"
cask "shottr"
cask "spotify", args: { appdir: "/Applications" }
cask "spotmenu"
cask "unity"
cask "unity-hub"
cask "vagrant"
cask "visual-studio-code", args: { appdir: "/Applications" }
cask "wezterm"
