alias ls="ls -a -G -F"
alias record-demo='xcrun simctl io booted recordVideo'
alias relog='exec $SHELL -l'
alias ..='cd ..'
# git
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gs='git status'
alias gsmain='git switch "$(git symbolic-ref refs/remotes/origin/HEAD | sed s@^refs/remotes/origin/@@)"'
alias gull='git pull origin "$(git symbolic-ref --short HEAD)"'
alias gpo='git push origin "$(git symbolic-ref --short HEAD)"'
alias gph='git push origin "$(git symbolic-ref --short HEAD)"'
alias gush='git push origin "$(git symbolic-ref --short HEAD)"'
alias gsc='git switch -c'
alias gsw='git switch'
alias vim='nvim'
alias vimcf='vim ~/.config/nvim'
alias dc='docker compose'
alias y='yarn'
alias dot='cd ~/dotfiles'
alias tm='tmux'
alias work='cd ~/workspace'
alias brewic="brew info --cask"
alias job="cd ~/projects/job"
alias me="cd ~/projects/me"
alias c="powered_cd"
alias rmf="rm -rf"
alias r="ruby"
alias heorku="heroku"

